# first stage builds vue
FROM node:19-alpine AS build-stage
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build

# second stage copies only the static dist files to nginx html dir

FROM linuxserver/swag:2.2.0 AS prod

RUN rm -rf /config/nginx/proxy-confs/*
RUN rm -rf /config/nginx/site-confs/*
COPY swag.nginx.conf /config/nginx/site-confs/default

COPY --from=build-stage /app/dist /config/www
