version: '3.3'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn culturizeweb.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.web
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    restart: unless-stopped
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile.swag
    ports:
      - 443:443
      - 80:80
    depends_on:
      - web
    env_file:
      - ./.env.nginx
    restart: unless-stopped

volumes:
  postgres_data:
