# Generated by Django 4.0 on 2022-02-05 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domain_id', models.AutoField(primary_key=True, serialize=False)),
                ('domain_name', models.CharField(max_length=50, unique=True)),
                ('configured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PathPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_index', models.IntegerField()),
                ('key_name', models.CharField(max_length=50)),
                ('auto_generate', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_parts', to='api.domain')),
            ],
            options={
                'ordering': ['path_index'],
                'unique_together': {('domain', 'key_name'), ('domain', 'path_index')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_url', models.URLField()),
                ('persistent_url', models.CharField(max_length=100)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.domain')),
            ],
            options={
                'unique_together': {('domain', 'persistent_url')},
            },
        ),
    ]
