# Generated by Django 4.0 on 2022-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_url', models.URLField()),
                ('persistent_url', models.URLField(unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='item',
            name='domain',
        ),
        migrations.AlterUniqueTogether(
            name='pathpart',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pathpart',
            name='domain',
        ),
        migrations.DeleteModel(
            name='Domain',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='PathPart',
        ),
    ]
