# Generated by Django 4.0 on 2023-02-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_persistent_url_requestlog_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
