# Generated by Django 4.0 on 2025-01-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_record_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=1)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(condition=models.Q(('enabled', False)), fields=['enabled'], name='not-enabled'),
        ),
    ]
