# Generated by Django 4.0 on 2025-07-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_export_record_not-enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='persistent_url',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='resource_url',
            field=models.URLField(max_length=500),
        ),
    ]
