# Generated by Django 4.2 on 2026-04-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_record_persistent_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='status',
            field=models.CharField(choices=[('NOT_TESTED', 'Not Tested'), ('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='NOT_TESTED', max_length=20),
        ),
    ]
