# Generated by Django 4.2 on 2026-04-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_record_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField()),
                ('start', models.DateTimeField()),
            ],
        ),
    ]
